import type { NextPage } from 'next'
import Head from 'next/head'
import Box from '@mui/material/Box'
import Card from '@mui/material/Card'
import Stack from '@mui/material/Stack'
import TextField from '@mui/material/TextField'
import Button from '@mui/material/Button'
import styles from '../styles/Home.module.css'
import { getUsers } from '../apolloClient/query'
import { useQuery } from '@apollo/client'
import Link from 'next/link'
import { ChangeEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/router'

interface ITextFieldError {
  error: boolean;
  helperText: string;
};

const defaultEmailError: ITextFieldError = {
  error: false,
  helperText: "",
};

const Login: NextPage = () => {
  const [email, setEmail] = useState("");
  const [submitForm, setSubmitForm] = useState(false);
  const [emailError, setEmailError] = useState<ITextFieldError>(defaultEmailError);
  const { data } = useQuery(getUsers, { variables: { email } });
  const router = useRouter();

  const handleEmailChange = (event: ChangeEvent<HTMLInputElement>) => setEmail(event.target.value);
  const handleBtnClick = () => {
    if (!email) {
      setEmailError({
        error: true,
        helperText: "Email field cannot be empty",
      });
    } else {
      setSubmitForm(true);
      setEmailError(defaultEmailError);
    }
  };

  useEffect(() => {
    if (submitForm) {
      if (data?.users.length) {
        router.push("/chats");
      } else {
        setEmailError({
          error: true,
          helperText: "Email was not found"
        });
      }
    }
    setSubmitForm(false);
  }, [submitForm, data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card elevation={3} sx={{ mt: -8, p: 2, pb: 5, width: "300px", backgroundColor: "#fffeee" }}>
          <Stack spacing={1}>
            <h3>Login to Chat-me</h3>
            <TextField variant="standard" label="Email" error={emailError.error} helperText={emailError.helperText} value={email} onChange={handleEmailChange} />
            <Button variant="contained" color='info' onClick={handleBtnClick}>Login</Button>
            <Box sx={{color: "#ccc", textAlign: "center"}}><Link href="/register"><a>Register here!!!</a></Link></Box>
          </Stack>
        </Card>
      </main>
    </div>
  )
}

export default Login
